# Generated by Django 5.0.4 on 2026-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(default='1234', max_length=128),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
