# Generated by Django 6.0.6 on 2026-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_group_password_alter_expense_id_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
